apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
  name: my-amq
spec:
  acceptors:
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
  console:
    expose: true
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 1
