apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-rest-app
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: yaml-samples/gitops
    repoURL: 'https://github.com/osa-ora/camel-k-samples'
    targetRevision: main
